<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 7,
                'brand_id' => 3,
                'title' => 'Áo thun nam đơn giản',
                'thumbnail' => 'products/thumbnails/HU3cse9OtbkYRg1mGyjiLtA2rQxqvmNbflS5nmLB.png',
                'description' => null,
                'product_type' => 'male',
                'material' => 'Cotton 100%',
                'min_price' => 99000.00,
                'max_price' => 115000.00,
                'has_discount' => 1,
                'max_discount' => 10,
                'status' => 1,
                'created_at' => '2025-11-17 10:57:24',
                'updated_at' => '2025-11-21 19:55:22',
            ],
            [
                'id' => 8,
                'brand_id' => 5,
                'title' => 'Áo thun nữ đơn giản',
                'thumbnail' => 'products/thumbnails/kh4J3ywv9UDVQiBBtPJhyj8ARJIshgCoWDIGoX7t.jpg',
                'description' => null,
                'product_type' => 'female',
                'material' => 'Cotton 97%',
                'min_price' => 100000.00,
                'max_price' => 110000.00,
                'has_discount' => 1,
                'max_discount' => 5,
                'status' => 1,
                'created_at' => '2025-11-20 19:49:21',
                'updated_at' => '2025-11-22 19:27:07',
            ],
            [
                'id' => 9,
                'brand_id' => 3,
                'title' => 'Áo thun nữ relax CHẠM',
                'thumbnail' => 'products/thumbnails/yPxila1B87onJLhFuBX5FZiivjt9HCpbdYDxj6xc.jpg',
                'description' => null,
                'product_type' => 'female',
                'material' => 'Cotton 100%',
                'min_price' => 200000.00,
                'max_price' => 210000.00,
                'has_discount' => 0,
                'max_discount' => 0,
                'status' => 1,
                'created_at' => '2025-11-22 19:59:38',
                'updated_at' => '2025-11-22 19:59:38',
            ],
            [
                'id' => 10,
                'brand_id' => 3,
                'title' => 'Áo Thun Nam Must Be Loved',
                'thumbnail' => 'products/thumbnails/DhGPwnPPFz4qW1SIllAjSkKBUa4l0K0GzdHGTeRU.jpg',
                'description' => null,
                'product_type' => 'male',
                'material' => '86.6% cotton và 13.4% polyester',
                'min_price' => 180000.00,
                'max_price' => 200000.00,
                'has_discount' => 0,
                'max_discount' => 0,
                'status' => 1,
                'created_at' => '2025-11-22 20:46:32',
                'updated_at' => '2025-11-22 20:46:32',
            ],
            [
                'id' => 11,
                'brand_id' => 5,
                'title' => 'Áo Thun Nam Ép Nhung Jazz',
                'thumbnail' => 'products/thumbnails/cEj9ZoBoBZxTiCFVZxwimA5H9hNKwa5bs0xuPPy5.jpg',
                'description' => null,
                'product_type' => 'male',
                'material' => 'Cotton 100%',
                'min_price' => 200000.00,
                'max_price' => 210000.00,
                'has_discount' => 0,
                'max_discount' => 0,
                'status' => 1,
                'created_at' => '2025-11-22 21:09:17',
                'updated_at' => '2025-11-22 21:09:17',
            ],
            [
                'id' => 12,
                'brand_id' => 3,
                'title' => 'Áo Thun Nữ Green X Typo Go Outside',
                'thumbnail' => 'products/thumbnails/nZeKUIY0k5W015SX8qc7k5m1RrOlUTH6F18BiVBW.jpg',
                'description' => null,
                'product_type' => 'female',
                'material' => '79,36% Cotton và 20,64% Iscra-S',
                'min_price' => 200000.00,
                'max_price' => 210000.00,
                'has_discount' => 0,
                'max_discount' => 0,
                'status' => 1,
                'created_at' => '2025-11-22 21:12:55',
                'updated_at' => '2025-11-22 21:12:55',
            ],
            [
                'id' => 17,
                'brand_id' => 5,
                'title' => 'Áo thun cặp YMMBF',
                'thumbnail' => 'products/thumbnails/kuj1Tg0ZK65dAWsdAML22nS1CDn8wfVpUKlhuWDX.jpg',
                'description' => null,
                'product_type' => 'couple',
                'material' => 'Cotton 100%',
                'min_price' => 200000.00,
                'max_price' => 210000.00,
                'has_discount' => 0,
                'max_discount' => 0,
                'status' => 1,
                'created_at' => '2025-11-27 20:00:12',
                'updated_at' => '2025-11-27 20:00:12',
            ],
            [
                'id' => 18,
                'brand_id' => 5,
                'title' => 'Áo thun cặp ONE-LOVE',
                'thumbnail' => 'products/thumbnails/FwFNi6dozx3JlASsbzrPjzk1hcDtHTjpHRAa6m2m.jpg',
                'description' => null,
                'product_type' => 'couple',
                'material' => 'Cotton 100%',
                'min_price' => 200000.00,
                'max_price' => 210000.00,
                'has_discount' => 0,
                'max_discount' => 0,
                'status' => 1,
                'created_at' => '2025-11-27 20:04:29',
                'updated_at' => '2025-11-27 20:04:29',
            ],
            [
                'id' => 19,
                'brand_id' => 5,
                'title' => 'Áo thun cặp MLOBF',
                'thumbnail' => 'products/thumbnails/mcHZn61Ge3WAyh2HhuKjU0LSFcawZ5rxowi21RrM.jpg',
                'description' => null,
                'product_type' => 'couple',
                'material' => 'Cotton 100%',
                'min_price' => 205000.00,
                'max_price' => 215000.00,
                'has_discount' => 0,
                'max_discount' => 0,
                'status' => 1,
                'created_at' => '2025-11-27 20:29:49',
                'updated_at' => '2025-11-27 22:44:08',
            ],
            [
                'id' => 20,
                'brand_id' => 5,
                'title' => 'Áo thun cặp ISH',
                'thumbnail' => 'products/thumbnails/er5HUzCAq4VAzf0kMhjxTBfIejWMNS12JnbdjU5V.jpg',
                'description' => null,
                'product_type' => 'couple',
                'material' => 'Cotton 100%',
                'min_price' => 200000.00,
                'max_price' => 210000.00,
                'has_discount' => 0,
                'max_discount' => 0,
                'status' => 1,
                'created_at' => '2025-11-27 20:31:17',
                'updated_at' => '2025-11-27 20:31:17',
            ],
            [
                'id' => 21,
                'brand_id' => 5,
                'title' => 'Áo Thun Nam Regular Typo Gain',
                'thumbnail' => 'products/thumbnails/ghQATLytf3Xo5QbAfokiQto480zIwHOXnAo3OUje.jpg',
                'description' => null,
                'product_type' => 'male',
                'material' => 'Cotton 100%',
                'min_price' => 230000.00,
                'max_price' => 240000.00,
                'has_discount' => 0,
                'max_discount' => 0,
                'status' => 1,
                'created_at' => '2025-11-27 21:16:56',
                'updated_at' => '2026-01-16 22:49:52',
            ],
            [
                'id' => 22,
                'brand_id' => 3,
                'title' => 'Áo Thun Nữ Relax Healing Nature',
                'thumbnail' => 'products/thumbnails/OsCjGp8PPS1y4DVRsGC5WHZrDwzX7FznzzOZQmfd.jpg',
                'description' => null,
                'product_type' => 'female',
                'material' => 'Cotton 100%',
                'min_price' => 250000.00,
                'max_price' => 260000.00,
                'has_discount' => 0,
                'max_discount' => 0,
                'status' => 1,
                'created_at' => '2025-11-27 21:21:40',
                'updated_at' => '2026-01-16 22:42:03',
            ],
        ]);
    }
}
